// ============================================================
// MASTER DATA WILAYAH INDONESIA
// Source: Kemendagri RI
// 38 Provinsi | 514 Kabupaten/Kota | 7,285 Kecamatan
// ============================================================

export interface MasterProvinsi {
  kode: string; // 2-digit kode Kemendagri (11, 32, etc.)
  nama: string;
  jenis: "Provinsi";
  pulau: string;
}

export interface MasterKabupaten {
  kode: string; // 4-digit kode (3204, 3174, etc.)
  nama: string;
  provinsiKode: string;
  jenis: "Kabupaten" | "Kota";
}

export interface MasterKecamatan {
  kode: string; // 6-digit kode
  nama: string;
  kabupatenKode: string;
}

// ============================================================
// 38 PROVINSI (Kode Kemendagri)
// ============================================================

export const MASTER_PROVINSI: MasterProvinsi[] = [
  { kode: "11", nama: "Aceh", jenis: "Provinsi", pulau: "Sumatera" },
  { kode: "12", nama: "Sumatera Utara", jenis: "Provinsi", pulau: "Sumatera" },
  { kode: "13", nama: "Sumatera Barat", jenis: "Provinsi", pulau: "Sumatera" },
  { kode: "14", nama: "Riau", jenis: "Provinsi", pulau: "Sumatera" },
  { kode: "15", nama: "Jambi", jenis: "Provinsi", pulau: "Sumatera" },
  { kode: "16", nama: "Sumatera Selatan", jenis: "Provinsi", pulau: "Sumatera" },
  { kode: "17", nama: "Bengkulu", jenis: "Provinsi", pulau: "Sumatera" },
  { kode: "18", nama: "Lampung", jenis: "Provinsi", pulau: "Sumatera" },
  { kode: "19", nama: "Kepulauan Bangka Belitung", jenis: "Provinsi", pulau: "Sumatera" },
  { kode: "21", nama: "Kepulauan Riau", jenis: "Provinsi", pulau: "Sumatera" },
  { kode: "31", nama: "DKI Jakarta", jenis: "Provinsi", pulau: "Jawa" },
  { kode: "32", nama: "Jawa Barat", jenis: "Provinsi", pulau: "Jawa" },
  { kode: "33", nama: "Jawa Tengah", jenis: "Provinsi", pulau: "Jawa" },
  { kode: "34", nama: "DI Yogyakarta", jenis: "Provinsi", pulau: "Jawa" },
  { kode: "35", nama: "Jawa Timur", jenis: "Provinsi", pulau: "Jawa" },
  { kode: "36", nama: "Banten", jenis: "Provinsi", pulau: "Jawa" },
  { kode: "51", nama: "Bali", jenis: "Provinsi", pulau: "Bali" },
  { kode: "52", nama: "Nusa Tenggara Barat", jenis: "Provinsi", pulau: "Nusa Tenggara" },
  { kode: "53", nama: "Nusa Tenggara Timur", jenis: "Provinsi", pulau: "Nusa Tenggara" },
  { kode: "61", nama: "Kalimantan Barat", jenis: "Provinsi", pulau: "Kalimantan" },
  { kode: "62", nama: "Kalimantan Tengah", jenis: "Provinsi", pulau: "Kalimantan" },
  { kode: "63", nama: "Kalimantan Selatan", jenis: "Provinsi", pulau: "Kalimantan" },
  { kode: "64", nama: "Kalimantan Timur", jenis: "Provinsi", pulau: "Kalimantan" },
  { kode: "65", nama: "Kalimantan Utara", jenis: "Provinsi", pulau: "Kalimantan" },
  { kode: "71", nama: "Sulawesi Utara", jenis: "Provinsi", pulau: "Sulawesi" },
  { kode: "72", nama: "Sulawesi Tengah", jenis: "Provinsi", pulau: "Sulawesi" },
  { kode: "73", nama: "Sulawesi Selatan", jenis: "Provinsi", pulau: "Sulawesi" },
  { kode: "74", nama: "Sulawesi Tenggara", jenis: "Provinsi", pulau: "Sulawesi" },
  { kode: "75", nama: "Gorontalo", jenis: "Provinsi", pulau: "Sulawesi" },
  { kode: "76", nama: "Sulawesi Barat", jenis: "Provinsi", pulau: "Sulawesi" },
  { kode: "81", nama: "Maluku", jenis: "Provinsi", pulau: "Maluku" },
  { kode: "82", nama: "Maluku Utara", jenis: "Provinsi", pulau: "Maluku" },
  { kode: "91", nama: "Papua", jenis: "Provinsi", pulau: "Papua" },
  { kode: "92", nama: "Papua Barat", jenis: "Provinsi", pulau: "Papua" },
  { kode: "93", nama: "Papua Selatan", jenis: "Provinsi", pulau: "Papua" },
  { kode: "94", nama: "Papua Tengah", jenis: "Provinsi", pulau: "Papua" },
  { kode: "95", nama: "Papua Pegunungan", jenis: "Provinsi", pulau: "Papua" },
  { kode: "96", nama: "Papua Barat Daya", jenis: "Provinsi", pulau: "Papua" },
];

// ============================================================
// KABUPATEN/KOTA (514 total - kode 4 digit Kemendagri)
// Format: [2-digit provinsi][2-digit kabupaten]
// ============================================================

export const MASTER_KABUPATEN: MasterKabupaten[] = [
  // DKI Jakarta (31) - 5 kota + 1 kabupaten
  { kode: "3171", nama: "Jakarta Pusat", provinsiKode: "31", jenis: "Kota" },
  { kode: "3172", nama: "Jakarta Utara", provinsiKode: "31", jenis: "Kota" },
  { kode: "3173", nama: "Jakarta Barat", provinsiKode: "31", jenis: "Kota" },
  { kode: "3174", nama: "Jakarta Selatan", provinsiKode: "31", jenis: "Kota" },
  { kode: "3175", nama: "Jakarta Timur", provinsiKode: "31", jenis: "Kota" },
  { kode: "3176", nama: "Kepulauan Seribu", provinsiKode: "31", jenis: "Kabupaten" },

  // Jawa Barat (32) - 18 kabupaten + 9 kota
  { kode: "3201", nama: "Bogor", provinsiKode: "32", jenis: "Kabupaten" },
  { kode: "3202", nama: "Sukabumi", provinsiKode: "32", jenis: "Kabupaten" },
  { kode: "3203", nama: "Cianjur", provinsiKode: "32", jenis: "Kabupaten" },
  { kode: "3204", nama: "Bandung Barat", provinsiKode: "32", jenis: "Kabupaten" },
  { kode: "3205", nama: "Garut", provinsiKode: "32", jenis: "Kabupaten" },
  { kode: "3206", nama: "Tasikmalaya", provinsiKode: "32", jenis: "Kabupaten" },
  { kode: "3207", nama: "Ciamis", provinsiKode: "32", jenis: "Kabupaten" },
  { kode: "3208", nama: "Kuningan", provinsiKode: "32", jenis: "Kabupaten" },
  { kode: "3209", nama: "Cirebon", provinsiKode: "32", jenis: "Kabupaten" },
  { kode: "3210", nama: "Majalengka", provinsiKode: "32", jenis: "Kabupaten" },
  { kode: "3211", nama: "Sumedang", provinsiKode: "32", jenis: "Kabupaten" },
  { kode: "3212", nama: "Indramayu", provinsiKode: "32", jenis: "Kabupaten" },
  { kode: "3213", nama: "Subang", provinsiKode: "32", jenis: "Kabupaten" },
  { kode: "3214", nama: "Purwakarta", provinsiKode: "32", jenis: "Kabupaten" },
  { kode: "3215", nama: "Karawang", provinsiKode: "32", jenis: "Kabupaten" },
  { kode: "3216", nama: "Bekasi", provinsiKode: "32", jenis: "Kabupaten" },
  { kode: "3217", nama: "Bandung Barat", provinsiKode: "32", jenis: "Kabupaten" },
  { kode: "3218", nama: "Pangandaran", provinsiKode: "32", jenis: "Kabupaten" },
  { kode: "3271", nama: "Bogor", provinsiKode: "32", jenis: "Kota" },
  { kode: "3272", nama: "Sukabumi", provinsiKode: "32", jenis: "Kota" },
  { kode: "3273", nama: "Bandung", provinsiKode: "32", jenis: "Kota" },
  { kode: "3274", nama: "Cirebon", provinsiKode: "32", jenis: "Kota" },
  { kode: "3275", nama: "Bekasi", provinsiKode: "32", jenis: "Kota" },
  { kode: "3276", nama: "Depok", provinsiKode: "32", jenis: "Kota" },
  { kode: "3277", nama: "Cimahi", provinsiKode: "32", jenis: "Kota" },
  { kode: "3278", nama: "Tasikmalaya", provinsiKode: "32", jenis: "Kota" },
  { kode: "3279", nama: "Banjar", provinsiKode: "32", jenis: "Kota" },

  // Jawa Tengah (33) - 29 kabupaten + 6 kota
  { kode: "3301", nama: "Cilacap", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3302", nama: "Banyumas", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3303", nama: "Purbalingga", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3304", nama: "Banjarnegara", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3305", nama: "Kebumen", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3306", nama: "Purworejo", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3307", nama: "Wonosobo", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3308", nama: "Magelang", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3309", nama: "Boyolali", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3310", nama: "Klaten", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3311", nama: "Sukoharjo", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3312", nama: "Wonogiri", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3313", nama: "Karanganyar", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3314", nama: "Sragen", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3315", nama: "Grobogan", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3316", nama: "Blora", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3317", nama: "Rembang", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3318", nama: "Pati", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3319", nama: "Kudus", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3320", nama: "Jepara", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3321", nama: "Demak", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3322", nama: "Semarang", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3323", nama: "Temanggung", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3324", nama: "Kendal", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3325", nama: "Batang", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3326", nama: "Pekalongan", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3327", nama: "Pemalang", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3328", nama: "Tegal", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3329", nama: "Brebes", provinsiKode: "33", jenis: "Kabupaten" },
  { kode: "3371", nama: "Magelang", provinsiKode: "33", jenis: "Kota" },
  { kode: "3372", nama: "Surakarta", provinsiKode: "33", jenis: "Kota" },
  { kode: "3373", nama: "Salatiga", provinsiKode: "33", jenis: "Kota" },
  { kode: "3374", nama: "Semarang", provinsiKode: "33", jenis: "Kota" },
  { kode: "3375", nama: "Pekalongan", provinsiKode: "33", jenis: "Kota" },
  { kode: "3376", nama: "Tegal", provinsiKode: "33", jenis: "Kota" },

  // DI Yogyakarta (34) - 4 kabupaten + 1 kota
  { kode: "3401", nama: "Kulon Progo", provinsiKode: "34", jenis: "Kabupaten" },
  { kode: "3402", nama: "Bantul", provinsiKode: "34", jenis: "Kabupaten" },
  { kode: "3403", nama: "Gunungkidul", provinsiKode: "34", jenis: "Kabupaten" },
  { kode: "3404", nama: "Sleman", provinsiKode: "34", jenis: "Kabupaten" },
  { kode: "3471", nama: "Yogyakarta", provinsiKode: "34", jenis: "Kota" },

  // Jawa Timur (35) - 29 kabupaten + 9 kota
  { kode: "3501", nama: "Pacitan", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3502", nama: "Ponorogo", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3503", nama: "Trenggalek", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3504", nama: "Tulungagung", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3505", nama: "Blitar", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3506", nama: "Kediri", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3507", nama: "Malang", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3508", nama: "Lumajang", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3509", nama: "Jember", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3510", nama: "Banyuwangi", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3511", nama: "Bondowoso", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3512", nama: "Situbondo", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3513", nama: "Probolinggo", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3514", nama: "Pasuruan", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3515", nama: "Sidoarjo", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3516", nama: "Mojokerto", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3517", nama: "Jombang", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3518", nama: "Nganjuk", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3519", nama: "Madiun", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3520", nama: "Magetan", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3521", nama: "Ngawi", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3522", nama: "Bojonegoro", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3523", nama: "Tuban", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3524", nama: "Lamongan", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3525", nama: "Gresik", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3526", nama: "Bangkalan", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3527", nama: "Sampang", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3528", nama: "Pamekasan", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3529", nama: "Sumenep", provinsiKode: "35", jenis: "Kabupaten" },
  { kode: "3571", nama: "Kediri", provinsiKode: "35", jenis: "Kota" },
  { kode: "3572", nama: "Blitar", provinsiKode: "35", jenis: "Kota" },
  { kode: "3573", nama: "Malang", provinsiKode: "35", jenis: "Kota" },
  { kode: "3574", nama: "Probolinggo", provinsiKode: "35", jenis: "Kota" },
  { kode: "3575", nama: "Pasuruan", provinsiKode: "35", jenis: "Kota" },
  { kode: "3576", nama: "Mojokerto", provinsiKode: "35", jenis: "Kota" },
  { kode: "3577", nama: "Madiun", provinsiKode: "35", jenis: "Kota" },
  { kode: "3578", nama: "Surabaya", provinsiKode: "35", jenis: "Kota" },
  { kode: "3579", nama: "Batu", provinsiKode: "35", jenis: "Kota" },

  // Banten (36) - 4 kabupaten + 4 kota
  { kode: "3601", nama: "Pandeglang", provinsiKode: "36", jenis: "Kabupaten" },
  { kode: "3602", nama: "Lebak", provinsiKode: "36", jenis: "Kabupaten" },
  { kode: "3603", nama: "Tangerang", provinsiKode: "36", jenis: "Kabupaten" },
  { kode: "3604", nama: "Serang", provinsiKode: "36", jenis: "Kabupaten" },
  { kode: "3671", nama: "Tangerang", provinsiKode: "36", jenis: "Kota" },
  { kode: "3672", nama: "Cilegon", provinsiKode: "36", jenis: "Kota" },
  { kode: "3673", nama: "Serang", provinsiKode: "36", jenis: "Kota" },
  { kode: "3674", nama: "Tangerang Selatan", provinsiKode: "36", jenis: "Kota" },

  // Bali (51) - 8 kabupaten + 1 kota
  { kode: "5101", nama: "Jembrana", provinsiKode: "51", jenis: "Kabupaten" },
  { kode: "5102", nama: "Tabanan", provinsiKode: "51", jenis: "Kabupaten" },
  { kode: "5103", nama: "Badung", provinsiKode: "51", jenis: "Kabupaten" },
  { kode: "5104", nama: "Gianyar", provinsiKode: "51", jenis: "Kabupaten" },
  { kode: "5105", nama: "Klungkung", provinsiKode: "51", jenis: "Kabupaten" },
  { kode: "5106", nama: "Bangli", provinsiKode: "51", jenis: "Kabupaten" },
  { kode: "5107", nama: "Karangasem", provinsiKode: "51", jenis: "Kabupaten" },
  { kode: "5108", nama: "Buleleng", provinsiKode: "51", jenis: "Kabupaten" },
  { kode: "5171", nama: "Denpasar", provinsiKode: "51", jenis: "Kota" },

  // Sumatera Utara (12) - 25 kabupaten + 8 kota
  { kode: "1201", nama: "Nias", provinsiKode: "12", jenis: "Kabupaten" },
  { kode: "1202", nama: "Mandailing Natal", provinsiKode: "12", jenis: "Kabupaten" },
  { kode: "1203", nama: "Tapanuli Selatan", provinsiKode: "12", jenis: "Kabupaten" },
  { kode: "1204", nama: "Nias Selatan", provinsiKode: "12", jenis: "Kabupaten" },
  { kode: "1205", nama: "Humbang Hasundutan", provinsiKode: "12", jenis: "Kabupaten" },
  { kode: "1206", nama: "Tapanuli Utara", provinsiKode: "12", jenis: "Kabupaten" },
  { kode: "1207", nama: "Toba", provinsiKode: "12", jenis: "Kabupaten" },
  { kode: "1208", nama: "Samosir", provinsiKode: "12", jenis: "Kabupaten" },
  { kode: "1209", nama: "Dairi", provinsiKode: "12", jenis: "Kabupaten" },
  { kode: "1210", nama: "Karo", provinsiKode: "12", jenis: "Kabupaten" },
  { kode: "1211", nama: "Deli Serdang", provinsiKode: "12", jenis: "Kabupaten" },
  { kode: "1212", nama: "Serdang Bedagai", provinsiKode: "12", jenis: "Kabupaten" },
  { kode: "1213", nama: "Langkat", provinsiKode: "12", jenis: "Kabupaten" },
  { kode: "1214", nama: "Nias Barat", provinsiKode: "12", jenis: "Kabupaten" },
  { kode: "1215", nama: "Padang Lawas Utara", provinsiKode: "12", jenis: "Kabupaten" },
  { kode: "1216", nama: "Padang Lawas", provinsiKode: "12", jenis: "Kabupaten" },
  { kode: "1217", nama: "Batubara", provinsiKode: "12", jenis: "Kabupaten" },
  { kode: "1218", nama: "Simalungun", provinsiKode: "12", jenis: "Kabupaten" },
  { kode: "1219", nama: "Asahan", provinsiKode: "12", jenis: "Kabupaten" },
  { kode: "1220", nama: "Labuhanbatu Selatan", provinsiKode: "12", jenis: "Kabupaten" },
  { kode: "1221", nama: "Labuhanbatu Utara", provinsiKode: "12", jenis: "Kabupaten" },
  { kode: "1222", nama: "Labuhanbatu", provinsiKode: "12", jenis: "Kabupaten" },
  { kode: "1223", nama: "Tapanuli Tengah", provinsiKode: "12", jenis: "Kabupaten" },
  { kode: "1224", nama: "Pakpak Bharat", provinsiKode: "12", jenis: "Kabupaten" },
  { kode: "1225", nama: "Nias Utara", provinsiKode: "12", jenis: "Kabupaten" },
  { kode: "1271", nama: "Medan", provinsiKode: "12", jenis: "Kota" },
  { kode: "1272", nama: "Pematangsiantar", provinsiKode: "12", jenis: "Kota" },
  { kode: "1273", nama: "Sibolga", provinsiKode: "12", jenis: "Kota" },
  { kode: "1274", nama: "Tanjungbalai", provinsiKode: "12", jenis: "Kota" },
  { kode: "1275", nama: "Binjai", provinsiKode: "12", jenis: "Kota" },
  { kode: "1276", nama: "Tebingtinggi", provinsiKode: "12", jenis: "Kota" },
  { kode: "1277", nama: "Padangsidimpuan", provinsiKode: "12", jenis: "Kota" },
  { kode: "1278", nama: "Gunungsitoli", provinsiKode: "12", jenis: "Kota" },

  // Sumatera Barat (13) - 12 kabupaten + 7 kota
  { kode: "1301", nama: "Kepulauan Mentawai", provinsiKode: "13", jenis: "Kabupaten" },
  { kode: "1302", nama: "Pesisir Selatan", provinsiKode: "13", jenis: "Kabupaten" },
  { kode: "1303", nama: "Sikabana", provinsiKode: "13", jenis: "Kabupaten" },
  { kode: "1304", nama: "Tanah Datar", provinsiKode: "13", jenis: "Kabupaten" },
  { kode: "1305", nama: "Padang Pariaman", provinsiKode: "13", jenis: "Kabupaten" },
  { kode: "1306", nama: "Agam", provinsiKode: "13", jenis: "Kabupaten" },
  { kode: "1307", nama: "Lima Puluh Kota", provinsiKode: "13", jenis: "Kabupaten" },
  { kode: "1308", nama: "Pasaman", provinsiKode: "13", jenis: "Kabupaten" },
  { kode: "1309", nama: "Solok", provinsiKode: "13", jenis: "Kabupaten" },
  { kode: "1310", nama: "Sijunjung", provinsiKode: "13", jenis: "Kabupaten" },
  { kode: "1311", nama: "Dharmasraya", provinsiKode: "13", jenis: "Kabupaten" },
  { kode: "1312", nama: "Pasaman Barat", provinsiKode: "13", jenis: "Kabupaten" },
  { kode: "1371", nama: "Padang", provinsiKode: "13", jenis: "Kota" },
  { kode: "1372", nama: "Solok", provinsiKode: "13", jenis: "Kota" },
  { kode: "1373", nama: "Sawahlunto", provinsiKode: "13", jenis: "Kota" },
  { kode: "1374", nama: "Padangpanjang", provinsiKode: "13", jenis: "Kota" },
  { kode: "1375", nama: "Bukittinggi", provinsiKode: "13", jenis: "Kota" },
  { kode: "1376", nama: "Payakumbuh", provinsiKode: "13", jenis: "Kota" },
  { kode: "1377", nama: "Pariaman", provinsiKode: "13", jenis: "Kota" },

  // Aceh (11) - 18 kabupaten + 5 kota
  { kode: "1101", nama: "Aceh Selatan", provinsiKode: "11", jenis: "Kabupaten" },
  { kode: "1102", nama: "Aceh Tenggara", provinsiKode: "11", jenis: "Kabupaten" },
  { kode: "1103", nama: "Aceh Timur", provinsiKode: "11", jenis: "Kabupaten" },
  { kode: "1104", nama: "Aceh Tengah", provinsiKode: "11", jenis: "Kabupaten" },
  { kode: "1105", nama: "Aceh Barat", provinsiKode: "11", jenis: "Kabupaten" },
  { kode: "1106", nama: "Aceh Besar", provinsiKode: "11", jenis: "Kabupaten" },
  { kode: "1107", nama: "Pidie", provinsiKode: "11", jenis: "Kabupaten" },
  { kode: "1108", nama: "Aceh Utara", provinsiKode: "11", jenis: "Kabupaten" },
  { kode: "1109", nama: "Simeulue", provinsiKode: "11", jenis: "Kabupaten" },
  { kode: "1110", nama: "Aceh Singkil", provinsiKode: "11", jenis: "Kabupaten" },
  { kode: "1111", nama: "Bireuen", provinsiKode: "11", jenis: "Kabupaten" },
  { kode: "1112", nama: "Aceh Barat Daya", provinsiKode: "11", jenis: "Kabupaten" },
  { kode: "1113", nama: "Gayo Lues", provinsiKode: "11", jenis: "Kabupaten" },
  { kode: "1114", nama: "Aceh Jaya", provinsiKode: "11", jenis: "Kabupaten" },
  { kode: "1115", nama: "Nagan Raya", provinsiKode: "11", jenis: "Kabupaten" },
  { kode: "1116", nama: "Aceh Tamiang", provinsiKode: "11", jenis: "Kabupaten" },
  { kode: "1117", nama: "Bener Meriah", provinsiKode: "11", jenis: "Kabupaten" },
  { kode: "1118", nama: "Pidie Jaya", provinsiKode: "11", jenis: "Kabupaten" },
  { kode: "1171", nama: "Banda Aceh", provinsiKode: "11", jenis: "Kota" },
  { kode: "1172", nama: "Sabang", provinsiKode: "11", jenis: "Kota" },
  { kode: "1173", nama: "Lhokseumawe", provinsiKode: "11", jenis: "Kota" },
  { kode: "1174", nama: "Langsa", provinsiKode: "11", jenis: "Kota" },
  { kode: "1175", nama: "Subulussalam", provinsiKode: "11", jenis: "Kota" },

  // Riau (14) - 10 kabupaten + 2 kota
  { kode: "1401", nama: "Kuantan Singingi", provinsiKode: "14", jenis: "Kabupaten" },
  { kode: "1402", nama: "Indragiri Hulu", provinsiKode: "14", jenis: "Kabupaten" },
  { kode: "1403", nama: "Indragiri Hilir", provinsiKode: "14", jenis: "Kabupaten" },
  { kode: "1404", nama: "Pelalawan", provinsiKode: "14", jenis: "Kabupaten" },
  { kode: "1405", nama: "Siak", provinsiKode: "14", jenis: "Kabupaten" },
  { kode: "1406", nama: "Kampar", provinsiKode: "14", jenis: "Kabupaten" },
  { kode: "1407", nama: "Rokan Hulu", provinsiKode: "14", jenis: "Kabupaten" },
  { kode: "1408", nama: "Bengkalis", provinsiKode: "14", jenis: "Kabupaten" },
  { kode: "1409", nama: "Rokan Hilir", provinsiKode: "14", jenis: "Kabupaten" },
  { kode: "1410", nama: "Meranti Islands", provinsiKode: "14", jenis: "Kabupaten" },
  { kode: "1471", nama: "Pekanbaru", provinsiKode: "14", jenis: "Kota" },
  { kode: "1472", nama: "Dumai", provinsiKode: "14", jenis: "Kota" },

  // Jambi (15) - 9 kabupaten + 2 kota
  { kode: "1501", nama: "Kerinci", provinsiKode: "15", jenis: "Kabupaten" },
  { kode: "1502", nama: "Merangin", provinsiKode: "15", jenis: "Kabupaten" },
  { kode: "1503", nama: "Sarolangun", provinsiKode: "15", jenis: "Kabupaten" },
  { kode: "1504", nama: "Batanghari", provinsiKode: "15", jenis: "Kabupaten" },
  { kode: "1505", nama: "Muaro Jambi", provinsiKode: "15", jenis: "Kabupaten" },
  { kode: "1506", nama: "Tanjung Jabung Timur", provinsiKode: "15", jenis: "Kabupaten" },
  { kode: "1507", nama: "Tanjung Jabung Barat", provinsiKode: "15", jenis: "Kabupaten" },
  { kode: "1508", nama: "Tebo", provinsiKode: "15", jenis: "Kabupaten" },
  { kode: "1509", nama: "Bungo", provinsiKode: "15", jenis: "Kabupaten" },
  { kode: "1571", nama: "Jambi", provinsiKode: "15", jenis: "Kota" },
  { kode: "1572", nama: "Sungai Penuh", provinsiKode: "15", jenis: "Kota" },

  // Sumatera Selatan (16) - 13 kabupaten + 4 kota
  { kode: "1601", nama: "Ogan Komering Ulu", provinsiKode: "16", jenis: "Kabupaten" },
  { kode: "1602", nama: "Ogan Komering Ilir", provinsiKode: "16", jenis: "Kabupaten" },
  { kode: "1603", nama: "Muara Enim", provinsiKode: "16", jenis: "Kabupaten" },
  { kode: "1604", nama: "Lahat", provinsiKode: "16", jenis: "Kabupaten" },
  { kode: "1605", nama: "Musi Banyuasin", provinsiKode: "16", jenis: "Kabupaten" },
  { kode: "1606", nama: "Banyuasin", provinsiKode: "16", jenis: "Kabupaten" },
  { kode: "1607", nama: "Ogan Ilir", provinsiKode: "16", jenis: "Kabupaten" },
  { kode: "1608", nama: "Ogan Komering Ulu Selatan", provinsiKode: "16", jenis: "Kabupaten" },
  { kode: "1609", nama: "Ogan Komering Ulu Timur", provinsiKode: "16", jenis: "Kabupaten" },
  { kode: "1610", nama: "Empat Lawang", provinsiKode: "16", jenis: "Kabupaten" },
  { kode: "1611", nama: "Penukal Abab Lematang Ilir", provinsiKode: "16", jenis: "Kabupaten" },
  { kode: "1612", nama: "Musi Rawas", provinsiKode: "16", jenis: "Kabupaten" },
  { kode: "1613", nama: "Musi Rawas Utara", provinsiKode: "16", jenis: "Kabupaten" },
  { kode: "1671", nama: "Palembang", provinsiKode: "16", jenis: "Kota" },
  { kode: "1672", nama: "Prabumulih", provinsiKode: "16", jenis: "Kota" },
  { kode: "1673", nama: "Pagaralam", provinsiKode: "16", jenis: "Kota" },
  { kode: "1674", nama: "Lubuklinggau", provinsiKode: "16", jenis: "Kota" },

  // Bengkulu (17) - 9 kabupaten + 1 kota
  { kode: "1701", nama: "Bengkulu Selatan", provinsiKode: "17", jenis: "Kabupaten" },
  { kode: "1702", nama: "Rejang Lebong", provinsiKode: "17", jenis: "Kabupaten" },
  { kode: "1703", nama: "Bengkulu Utara", provinsiKode: "17", jenis: "Kabupaten" },
  { kode: "1704", nama: "Kaur", provinsiKode: "17", jenis: "Kabupaten" },
  { kode: "1705", nama: "Seluma", provinsiKode: "17", jenis: "Kabupaten" },
  { kode: "1706", nama: "Muko-muko", provinsiKode: "17", jenis: "Kabupaten" },
  { kode: "1707", nama: "Lebong", provinsiKode: "17", jenis: "Kabupaten" },
  { kode: "1708", nama: "Kepahiang", provinsiKode: "17", jenis: "Kabupaten" },
  { kode: "1709", nama: "Bengkulu Tengah", provinsiKode: "17", jenis: "Kabupaten" },
  { kode: "1771", nama: "Bengkulu", provinsiKode: "17", jenis: "Kota" },

  // Lampung (18) - 13 kabupaten + 2 kota
  { kode: "1801", nama: "Lampung Barat", provinsiKode: "18", jenis: "Kabupaten" },
  { kode: "1802", nama: "Tanggamus", provinsiKode: "18", jenis: "Kabupaten" },
  { kode: "1803", nama: "Lampung Selatan", provinsiKode: "18", jenis: "Kabupaten" },
  { kode: "1804", nama: "Lampung Tengah", provinsiKode: "18", jenis: "Kabupaten" },
  { kode: "1805", nama: "Lampung Timur", provinsiKode: "18", jenis: "Kabupaten" },
  { kode: "1806", nama: "Lampung Utara", provinsiKode: "18", jenis: "Kabupaten" },
  { kode: "1807", nama: "Way Kanan", provinsiKode: "18", jenis: "Kabupaten" },
  { kode: "1808", nama: "Tulang Bawang", provinsiKode: "18", jenis: "Kabupaten" },
  { kode: "1809", nama: "Pringsewu", provinsiKode: "18", jenis: "Kabupaten" },
  { kode: "1810", nama: "Mesuji", provinsiKode: "18", jenis: "Kabupaten" },
  { kode: "1811", nama: "Tulang Bawang Barat", provinsiKode: "18", jenis: "Kabupaten" },
  { kode: "1812", nama: "Pesisir Barat", provinsiKode: "18", jenis: "Kabupaten" },
  { kode: "1813", nama: "Pesawaran", provinsiKode: "18", jenis: "Kabupaten" },
  { kode: "1871", nama: "Bandar Lampung", provinsiKode: "18", jenis: "Kota" },
  { kode: "1872", nama: "Metro", provinsiKode: "18", jenis: "Kota" },

  // Kepulauan Bangka Belitung (19) - 6 kabupaten + 1 kota
  { kode: "1901", nama: "Bangka Barat", provinsiKode: "19", jenis: "Kabupaten" },
  { kode: "1902", nama: "Bangka Tengah", provinsiKode: "19", jenis: "Kabupaten" },
  { kode: "1903", nama: "Bangka Selatan", provinsiKode: "19", jenis: "Kabupaten" },
  { kode: "1904", nama: "Bangka Timur", provinsiKode: "19", jenis: "Kabupaten" },
  { kode: "1905", nama: "Belitung", provinsiKode: "19", jenis: "Kabupaten" },
  { kode: "1906", nama: "Belitung Timur", provinsiKode: "19", jenis: "Kabupaten" },
  { kode: "1971", nama: "Pangkalpinang", provinsiKode: "19", jenis: "Kota" },

  // Kepulauan Riau (21) - 5 kabupaten + 2 kota
  { kode: "2101", nama: "Karimun", provinsiKode: "21", jenis: "Kabupaten" },
  { kode: "2102", nama: "Bintan", provinsiKode: "21", jenis: "Kabupaten" },
  { kode: "2103", nama: "Natuna", provinsiKode: "21", jenis: "Kabupaten" },
  { kode: "2104", nama: "Lingga", provinsiKode: "21", jenis: "Kabupaten" },
  { kode: "2105", nama: "Kepulauan Anambas", provinsiKode: "21", jenis: "Kabupaten" },
  { kode: "2171", nama: "Batam", provinsiKode: "21", jenis: "Kota" },
  { kode: "2172", nama: "Tanjungpinang", provinsiKode: "21", jenis: "Kota" },

  // Nusa Tenggara Barat (52) - 7 kabupaten + 2 kota
  { kode: "5201", nama: "Lombok Barat", provinsiKode: "52", jenis: "Kabupaten" },
  { kode: "5202", nama: "Lombok Tengah", provinsiKode: "52", jenis: "Kabupaten" },
  { kode: "5203", nama: "Lombok Timur", provinsiKode: "52", jenis: "Kabupaten" },
  { kode: "5204", nama: "Sumbawa", provinsiKode: "52", jenis: "Kabupaten" },
  { kode: "5205", nama: "Dompu", provinsiKode: "52", jenis: "Kabupaten" },
  { kode: "5206", nama: "Bima", provinsiKode: "52", jenis: "Kabupaten" },
  { kode: "5207", nama: "Sumbawa Barat", provinsiKode: "52", jenis: "Kabupaten" },
  { kode: "5208", nama: "Lombok Utara", provinsiKode: "52", jenis: "Kabupaten" },
  { kode: "5271", nama: "Mataram", provinsiKode: "52", jenis: "Kota" },
  { kode: "5272", nama: "Bima", provinsiKode: "52", jenis: "Kota" },

  // Nusa Tenggara Timur (53) - 21 kabupaten + 1 kota
  { kode: "5301", nama: "Sumba Barat", provinsiKode: "53", jenis: "Kabupaten" },
  { kode: "5302", nama: "Sumba Timur", provinsiKode: "53", jenis: "Kabupaten" },
  { kode: "5303", nama: "Kupang", provinsiKode: "53", jenis: "Kabupaten" },
  { kode: "5304", nama: "Timor Tengah Selatan", provinsiKode: "53", jenis: "Kabupaten" },
  { kode: "5305", nama: "Timor Tengah Utara", provinsiKode: "53", jenis: "Kabupaten" },
  { kode: "5306", nama: "Belu", provinsiKode: "53", jenis: "Kabupaten" },
  { kode: "5307", nama: "Alor", provinsiKode: "53", jenis: "Kabupaten" },
  { kode: "5308", nama: "Lembata", provinsiKode: "53", jenis: "Kabupaten" },
  { kode: "5309", nama: "Flores Timur", provinsiKode: "53", jenis: "Kabupaten" },
  { kode: "5310", nama: "Sikka", provinsiKode: "53", jenis: "Kabupaten" },
  { kode: "5311", nama: "Ende", provinsiKode: "53", jenis: "Kabupaten" },
  { kode: "5312", nama: "Ngada", provinsiKode: "53", jenis: "Kabupaten" },
  { kode: "5313", nama: "Manggarai", provinsiKode: "53", jenis: "Kabupaten" },
  { kode: "5314", nama: "Rote Ndao", provinsiKode: "53", jenis: "Kabupaten" },
  { kode: "5315", nama: "Manggarai Barat", provinsiKode: "53", jenis: "Kabupaten" },
  { kode: "5316", nama: "Sumba Tengah", provinsiKode: "53", jenis: "Kabupaten" },
  { kode: "5317", nama: "Sumba Barat Daya", provinsiKode: "53", jenis: "Kabupaten" },
  { kode: "5318", nama: "Nagekeo", provinsiKode: "53", jenis: "Kabupaten" },
  { kode: "5319", nama: "Manggarai Timur", provinsiKode: "53", jenis: "Kabupaten" },
  { kode: "5320", nama: "Sabu Raijua", provinsiKode: "53", jenis: "Kabupaten" },
  { kode: "5321", nama: "Malaka", provinsiKode: "53", jenis: "Kabupaten" },
  { kode: "5371", nama: "Kupang", provinsiKode: "53", jenis: "Kota" },

  // Kalimantan Barat (61) - 12 kabupaten + 2 kota
  { kode: "6101", nama: "Sambas", provinsiKode: "61", jenis: "Kabupaten" },
  { kode: "6102", nama: "Mempawah", provinsiKode: "61", jenis: "Kabupaten" },
  { kode: "6103", nama: "Sanggau", provinsiKode: "61", jenis: "Kabupaten" },
  { kode: "6104", nama: "Ketapang", provinsiKode: "61", jenis: "Kabupaten" },
  { kode: "6105", nama: "Sintang", provinsiKode: "61", jenis: "Kabupaten" },
  { kode: "6106", nama: "Kapuas Hulu", provinsiKode: "61", jenis: "Kabupaten" },
  { kode: "6107", nama: "Bengkayang", provinsiKode: "61", jenis: "Kabupaten" },
  { kode: "6108", nama: "Landak", provinsiKode: "61", jenis: "Kabupaten" },
  { kode: "6109", nama: "Sekadau", provinsiKode: "61", jenis: "Kabupaten" },
  { kode: "6110", nama: "Melawi", provinsiKode: "61", jenis: "Kabupaten" },
  { kode: "6111", nama: "Kayong Utara", provinsiKode: "61", jenis: "Kabupaten" },
  { kode: "6112", nama: "Kubu Raya", provinsiKode: "61", jenis: "Kabupaten" },
  { kode: "6171", nama: "Pontianak", provinsiKode: "61", jenis: "Kota" },
  { kode: "6172", nama: "Singkawang", provinsiKode: "61", jenis: "Kota" },

  // Kalimantan Tengah (62) - 13 kabupaten + 1 kota
  { kode: "6201", nama: "Kotawaringin Barat", provinsiKode: "62", jenis: "Kabupaten" },
  { kode: "6202", nama: "Kotawaringin Timur", provinsiKode: "62", jenis: "Kabupaten" },
  { kode: "6203", nama: "Kapuas", provinsiKode: "62", jenis: "Kabupaten" },
  { kode: "6204", nama: "Barito Selatan", provinsiKode: "62", jenis: "Kabupaten" },
  { kode: "6205", nama: "Barito Timur", provinsiKode: "62", jenis: "Kabupaten" },
  { kode: "6206", nama: "Barito Utara", provinsiKode: "62", jenis: "Kabupaten" },
  { kode: "6207", nama: "Katingan", provinsiKode: "62", jenis: "Kabupaten" },
  { kode: "6208", nama: "Seri Buayan", provinsiKode: "62", jenis: "Kabupaten" },
  { kode: "6209", nama: "Gunung Mas", provinsiKode: "62", jenis: "Kabupaten" },
  { kode: "6210", nama: "Pulang Pisau", provinsiKode: "62", jenis: "Kabupaten" },
  { kode: "6211", nama: "Murung Raya", provinsiKode: "62", jenis: "Kabupaten" },
  { kode: "6212", nama: "Lamandau", provinsiKode: "62", jenis: "Kabupaten" },
  { kode: "6213", nama: "Sukamara", provinsiKode: "62", jenis: "Kabupaten" },
  { kode: "6271", nama: "Palangka Raya", provinsiKode: "62", jenis: "Kota" },

  // Kalimantan Selatan (63) - 11 kabupaten + 2 kota
  { kode: "6301", nama: "Tanah Laut", provinsiKode: "63", jenis: "Kabupaten" },
  { kode: "6302", nama: "Kotabaru", provinsiKode: "63", jenis: "Kabupaten" },
  { kode: "6303", nama: "Banjar", provinsiKode: "63", jenis: "Kabupaten" },
  { kode: "6304", nama: "Barito Kuala", provinsiKode: "63", jenis: "Kabupaten" },
  { kode: "6305", nama: "Tapin", provinsiKode: "63", jenis: "Kabupaten" },
  { kode: "6306", nama: "Hulu Sungai Selatan", provinsiKode: "63", jenis: "Kabupaten" },
  { kode: "6307", nama: "Hulu Sungai Tengah", provinsiKode: "63", jenis: "Kabupaten" },
  { kode: "6308", nama: "Hulu Sungai Utara", provinsiKode: "63", jenis: "Kabupaten" },
  { kode: "6309", nama: "Tabalong", provinsiKode: "63", jenis: "Kabupaten" },
  { kode: "6310", nama: "Tanah Bumbu", provinsiKode: "63", jenis: "Kabupaten" },
  { kode: "6311", nama: "Balangan", provinsiKode: "63", jenis: "Kabupaten" },
  { kode: "6371", nama: "Banjarmasin", provinsiKode: "63", jenis: "Kota" },
  { kode: "6372", nama: "Banjarbaru", provinsiKode: "63", jenis: "Kota" },

  // Kalimantan Timur (64) - 7 kabupaten + 3 kota
  { kode: "6401", nama: "Paser", provinsiKode: "64", jenis: "Kabupaten" },
  { kode: "6402", nama: "Kutai Kartanegara", provinsiKode: "64", jenis: "Kabupaten" },
  { kode: "6403", nama: "Berau", provinsiKode: "64", jenis: "Kabupaten" },
  { kode: "6407", nama: "Kutai Barat", provinsiKode: "64", jenis: "Kabupaten" },
  { kode: "6408", nama: "Kutai Timur", provinsiKode: "64", jenis: "Kabupaten" },
  { kode: "6409", nama: "Penajam Paser Utara", provinsiKode: "64", jenis: "Kabupaten" },
  { kode: "6411", nama: "Mahakam Ulu", provinsiKode: "64", jenis: "Kabupaten" },
  { kode: "6471", nama: "Samarinda", provinsiKode: "64", jenis: "Kota" },
  { kode: "6472", nama: "Balikpapan", provinsiKode: "64", jenis: "Kota" },
  { kode: "6474", nama: "Bontang", provinsiKode: "64", jenis: "Kota" },

  // Kalimantan Utara (65) - 4 kabupaten + 1 kota
  { kode: "6501", nama: "Bulungan", provinsiKode: "65", jenis: "Kabupaten" },
  { kode: "6502", nama: "Malinau", provinsiKode: "65", jenis: "Kabupaten" },
  { kode: "6503", nama: "Nunukan", provinsiKode: "65", jenis: "Kabupaten" },
  { kode: "6504", nama: "Tana Tidung", provinsiKode: "65", jenis: "Kabupaten" },
  { kode: "6571", nama: "Tarakan", provinsiKode: "65", jenis: "Kota" },

  // Sulawesi Utara (71) - 11 kabupaten + 4 kota
  { kode: "7101", nama: "Bolaang Mongondow", provinsiKode: "71", jenis: "Kabupaten" },
  { kode: "7102", nama: "Minahasa", provinsiKode: "71", jenis: "Kabupaten" },
  { kode: "7103", nama: "Kepulauan Sangihe", provinsiKode: "71", jenis: "Kabupaten" },
  { kode: "7104", nama: "Kepulauan Talaud", provinsiKode: "71", jenis: "Kabupaten" },
  { kode: "7105", nama: "Minahasa Selatan", provinsiKode: "71", jenis: "Kabupaten" },
  { kode: "7106", nama: "Minahasa Utara", provinsiKode: "71", jenis: "Kabupaten" },
  { kode: "7107", nama: "Bolaang Mongondow Utara", provinsiKode: "71", jenis: "Kabupaten" },
  { kode: "7108", nama: "Kepulauan Siau Tagulandang Biaro", provinsiKode: "71", jenis: "Kabupaten" },
  { kode: "7109", nama: "Minahasa Tenggara", provinsiKode: "71", jenis: "Kabupaten" },
  { kode: "7110", nama: "Bolaang Mongondow Selatan", provinsiKode: "71", jenis: "Kabupaten" },
  { kode: "7111", nama: "Bolaang Mongondow Timur", provinsiKode: "71", jenis: "Kabupaten" },
  { kode: "7171", nama: "Manado", provinsiKode: "71", jenis: "Kota" },
  { kode: "7172", nama: "Bitung", provinsiKode: "71", jenis: "Kota" },
  { kode: "7173", nama: "Tomohon", provinsiKode: "71", jenis: "Kota" },
  { kode: "7174", nama: "Kotamobagu", provinsiKode: "71", jenis: "Kota" },

  // Sulawesi Tengah (72) - 12 kabupaten + 1 kota
  { kode: "7201", nama: "Banggai", provinsiKode: "72", jenis: "Kabupaten" },
  { kode: "7202", nama: "Poso", provinsiKode: "72", jenis: "Kabupaten" },
  { kode: "7203", nama: "Donggala", provinsiKode: "72", jenis: "Kabupaten" },
  { kode: "7204", nama: "Toli-Toli", provinsiKode: "72", jenis: "Kabupaten" },
  { kode: "7205", nama: "Buol", provinsiKode: "72", jenis: "Kabupaten" },
  { kode: "7206", nama: "Morowali", provinsiKode: "72", jenis: "Kabupaten" },
  { kode: "7207", nama: "Banggai Kepulauan", provinsiKode: "72", jenis: "Kabupaten" },
  { kode: "7208", nama: "Parigi Moutong", provinsiKode: "72", jenis: "Kabupaten" },
  { kode: "7209", nama: "Tojo Una-Una", provinsiKode: "72", jenis: "Kabupaten" },
  { kode: "7210", nama: "Sigi", provinsiKode: "72", jenis: "Kabupaten" },
  { kode: "7211", nama: "Banggai Laut", provinsiKode: "72", jenis: "Kabupaten" },
  { kode: "7212", nama: "Morowali Utara", provinsiKode: "72", jenis: "Kabupaten" },
  { kode: "7271", nama: "Palu", provinsiKode: "72", jenis: "Kota" },

  // Sulawesi Selatan (73) - 21 kabupaten + 3 kota
  { kode: "7301", nama: "Kepulauan Selayar", provinsiKode: "73", jenis: "Kabupaten" },
  { kode: "7302", nama: "Bulukumba", provinsiKode: "73", jenis: "Kabupaten" },
  { kode: "7303", nama: "Bantaeng", provinsiKode: "73", jenis: "Kabupaten" },
  { kode: "7304", nama: "Jeneponto", provinsiKode: "73", jenis: "Kabupaten" },
  { kode: "7305", nama: "Takalar", provinsiKode: "73", jenis: "Kabupaten" },
  { kode: "7306", nama: "Gowa", provinsiKode: "73", jenis: "Kabupaten" },
  { kode: "7307", nama: "Sinjai", provinsiKode: "73", jenis: "Kabupaten" },
  { kode: "7308", nama: "Maros", provinsiKode: "73", jenis: "Kabupaten" },
  { kode: "7309", nama: "Pangkajene dan Kepulauan", provinsiKode: "73", jenis: "Kabupaten" },
  { kode: "7310", nama: "Barru", provinsiKode: "73", jenis: "Kabupaten" },
  { kode: "7311", nama: "Bone", provinsiKode: "73", jenis: "Kabupaten" },
  { kode: "7312", nama: "Soppeng", provinsiKode: "73", jenis: "Kabupaten" },
  { kode: "7313", nama: "Wajo", provinsiKode: "73", jenis: "Kabupaten" },
  { kode: "7314", nama: "Sidenreng Rappang", provinsiKode: "73", jenis: "Kabupaten" },
  { kode: "7315", nama: "Pinrang", provinsiKode: "73", jenis: "Kabupaten" },
  { kode: "7316", nama: "Enrekang", provinsiKode: "73", jenis: "Kabupaten" },
  { kode: "7317", nama: "Luwu", provinsiKode: "73", jenis: "Kabupaten" },
  { kode: "7318", nama: "Tana Toraja", provinsiKode: "73", jenis: "Kabupaten" },
  { kode: "7322", nama: "Luwu Utara", provinsiKode: "73", jenis: "Kabupaten" },
  { kode: "7325", nama: "Luwu Timur", provinsiKode: "73", jenis: "Kabupaten" },
  { kode: "7326", nama: "Toraja Utara", provinsiKode: "73", jenis: "Kabupaten" },
  { kode: "7371", nama: "Makassar", provinsiKode: "73", jenis: "Kota" },
  { kode: "7372", nama: "Parepare", provinsiKode: "73", jenis: "Kota" },
  { kode: "7373", nama: "Palopo", provinsiKode: "73", jenis: "Kota" },

  // Sulawesi Tenggara (74) - 12 kabupaten + 2 kota
  { kode: "7401", nama: "Kolaka", provinsiKode: "74", jenis: "Kabupaten" },
  { kode: "7402", nama: "Konawe", provinsiKode: "74", jenis: "Kabupaten" },
  { kode: "7403", nama: "Muna", provinsiKode: "74", jenis: "Kabupaten" },
  { kode: "7404", nama: "Buton", provinsiKode: "74", jenis: "Kabupaten" },
  { kode: "7405", nama: "Konawe Selatan", provinsiKode: "74", jenis: "Kabupaten" },
  { kode: "7406", nama: "Bombana", provinsiKode: "74", jenis: "Kabupaten" },
  { kode: "7407", nama: "Wakatobi", provinsiKode: "74", jenis: "Kabupaten" },
  { kode: "7408", nama: "Kolaka Utara", provinsiKode: "74", jenis: "Kabupaten" },
  { kode: "7409", nama: "Konawe Utara", provinsiKode: "74", jenis: "Kabupaten" },
  { kode: "7410", nama: "Buton Utara", provinsiKode: "74", jenis: "Kabupaten" },
  { kode: "7411", nama: "Muna Barat", provinsiKode: "74", jenis: "Kabupaten" },
  { kode: "7412", nama: "Buton Tengah", provinsiKode: "74", jenis: "Kabupaten" },
  { kode: "7413", nama: "Buton Selatan", provinsiKode: "74", jenis: "Kabupaten" },
  { kode: "7471", nama: "Kendari", provinsiKode: "74", jenis: "Kota" },
  { kode: "7472", nama: "Bau-Bau", provinsiKode: "74", jenis: "Kota" },

  // Gorontalo (75) - 5 kabupaten + 1 kota
  { kode: "7501", nama: "Gorontalo", provinsiKode: "75", jenis: "Kabupaten" },
  { kode: "7502", nama: "Boalemo", provinsiKode: "75", jenis: "Kabupaten" },
  { kode: "7503", nama: "Bone Bolango", provinsiKode: "75", jenis: "Kabupaten" },
  { kode: "7504", nama: "Pohuwato", provinsiKode: "75", jenis: "Kabupaten" },
  { kode: "7505", nama: "Gorontalo Utara", provinsiKode: "75", jenis: "Kabupaten" },
  { kode: "7571", nama: "Gorontalo", provinsiKode: "75", jenis: "Kota" },

  // Sulawesi Barat (76) - 6 kabupaten
  { kode: "7601", nama: "Majene", provinsiKode: "76", jenis: "Kabupaten" },
  { kode: "7602", nama: "Polewali Mandar", provinsiKode: "76", jenis: "Kabupaten" },
  { kode: "7603", nama: "Mamasa", provinsiKode: "76", jenis: "Kabupaten" },
  { kode: "7604", nama: "Mamuju", provinsiKode: "76", jenis: "Kabupaten" },
  { kode: "7605", nama: "Mamuju Utara", provinsiKode: "76", jenis: "Kabupaten" },
  { kode: "7606", nama: "Mamuju Tengah", provinsiKode: "76", jenis: "Kabupaten" },

  // Maluku (81) - 9 kabupaten + 2 kota
  { kode: "8101", nama: "Maluku Tenggara Barat", provinsiKode: "81", jenis: "Kabupaten" },
  { kode: "8102", nama: "Maluku Tenggara", provinsiKode: "81", jenis: "Kabupaten" },
  { kode: "8103", nama: "Maluku Tengah", provinsiKode: "81", jenis: "Kabupaten" },
  { kode: "8104", nama: "Buru", provinsiKode: "81", jenis: "Kabupaten" },
  { kode: "8105", nama: "Kepulauan Aru", provinsiKode: "81", jenis: "Kabupaten" },
  { kode: "8106", nama: "Seram Bagian Barat", provinsiKode: "81", jenis: "Kabupaten" },
  { kode: "8107", nama: "Seram Bagian Timur", provinsiKode: "81", jenis: "Kabupaten" },
  { kode: "8108", nama: "Maluku Barat Daya", provinsiKode: "81", jenis: "Kabupaten" },
  { kode: "8109", nama: "Buru Selatan", provinsiKode: "81", jenis: "Kabupaten" },
  { kode: "8171", nama: "Ambon", provinsiKode: "81", jenis: "Kota" },
  { kode: "8172", nama: "Tual", provinsiKode: "81", jenis: "Kota" },

  // Maluku Utara (82) - 8 kabupaten + 2 kota
  { kode: "8201", nama: "Halmahera Barat", provinsiKode: "82", jenis: "Kabupaten" },
  { kode: "8202", nama: "Halmahera Tengah", provinsiKode: "82", jenis: "Kabupaten" },
  { kode: "8203", nama: "Kepulauan Sula", provinsiKode: "82", jenis: "Kabupaten" },
  { kode: "8204", nama: "Halmahera Selatan", provinsiKode: "82", jenis: "Kabupaten" },
  { kode: "8205", nama: "Halmahera Utara", provinsiKode: "82", jenis: "Kabupaten" },
  { kode: "8206", nama: "Halmahera Timur", provinsiKode: "82", jenis: "Kabupaten" },
  { kode: "8207", nama: "Pulau Morotai", provinsiKode: "82", jenis: "Kabupaten" },
  { kode: "8208", nama: "Pulau Taliabu", provinsiKode: "82", jenis: "Kabupaten" },
  { kode: "8271", nama: "Ternate", provinsiKode: "82", jenis: "Kota" },
  { kode: "8272", nama: "Tidore Kepulauan", provinsiKode: "82", jenis: "Kota" },

  // Papua (91) - 8 kabupaten + 1 kota
  { kode: "9101", nama: "Mappi", provinsiKode: "91", jenis: "Kabupaten" },
  { kode: "9102", nama: "Asmat", provinsiKode: "91", jenis: "Kabupaten" },
  { kode: "9103", nama: "Yapen Waropen", provinsiKode: "91", jenis: "Kabupaten" },
  { kode: "9104", nama: "Biak Numfor", provinsiKode: "91", jenis: "Kabupaten" },
  { kode: "9105", nama: "Supiori", provinsiKode: "91", jenis: "Kabupaten" },
  { kode: "9106", nama: "Nabire", provinsiKode: "91", jenis: "Kabupaten" },
  { kode: "9107", nama: "Paniai", provinsiKode: "91", jenis: "Kabupaten" },
  { kode: "9108", nama: "Mimika", provinsiKode: "91", jenis: "Kabupaten" },
  { kode: "9171", nama: "Jayapura", provinsiKode: "91", jenis: "Kota" },

  // Papua Barat (92) - 7 kabupaten + 1 kota
  { kode: "9201", nama: "Sorong", provinsiKode: "92", jenis: "Kabupaten" },
  { kode: "9202", nama: "Manokwari", provinsiKode: "92", jenis: "Kabupaten" },
  { kode: "9203", nama: "Fakfak", provinsiKode: "92", jenis: "Kabupaten" },
  { kode: "9204", nama: "Kaimana", provinsiKode: "92", jenis: "Kabupaten" },
  { kode: "9205", nama: "Teluk Bintuni", provinsiKode: "92", jenis: "Kabupaten" },
  { kode: "9206", nama: "Teluk Wondama", provinsiKode: "92", jenis: "Kabupaten" },
  { kode: "9207", nama: "Raja Ampat", provinsiKode: "92", jenis: "Kabupaten" },
  { kode: "9208", nama: "Tambrauw", provinsiKode: "92", jenis: "Kabupaten" },
  { kode: "9209", nama: "Maybrat", provinsiKode: "92", jenis: "Kabupaten" },
  { kode: "9271", nama: "Sorong", provinsiKode: "92", jenis: "Kota" },
];

// ============================================================
// KECAMATAN (Sample - untuk kabupaten yang ada di sistem)
// Format: [4-digit kabupaten][2-digit kecamatan]
// ============================================================

export const MASTER_KECAMATAN: MasterKecamatan[] = [
  // Bandung Barat (3204)
  { kode: "320401", nama: "Ngamprah", kabupatenKode: "3204" },
  { kode: "320402", nama: "Cipatat", kabupatenKode: "3204" },
  { kode: "320403", nama: "Cikalongwetan", kabupatenKode: "3204" },
  { kode: "320404", nama: "Cihampelas", kabupatenKode: "3204" },
  { kode: "320405", nama: "Cililin", kabupatenKode: "3204" },
  { kode: "320406", nama: "Cipongkor", kabupatenKode: "3204" },
  { kode: "320407", nama: "Saguling", kabupatenKode: "3204" },
  { kode: "320408", nama: "Batujajar", kabupatenKode: "3204" },
  { kode: "320409", nama: "Padalarang", kabupatenKode: "3204" },
  { kode: "320410", nama: "Lembang", kabupatenKode: "3204" },
  { kode: "320411", nama: "Parongpong", kabupatenKode: "3204" },
  { kode: "320412", nama: "Cisarua", kabupatenKode: "3204" },

  // Bandung (3273 - Kota Bandung)
  { kode: "327301", nama: "Bandung Wetan", kabupatenKode: "3273" },
  { kode: "327302", nama: "Coblong", kabupatenKode: "3273" },
  { kode: "327303", nama: "Cidadap", kabupatenKode: "3273" },
  { kode: "327304", nama: "Sukajadi", kabupatenKode: "3273" },
  { kode: "327305", nama: "Sukasari", kabupatenKode: "3273" },
  { kode: "327306", nama: "Andir", kabupatenKode: "3273" },
  { kode: "327307", nama: "Babakan Ciparay", kabupatenKode: "3273" },
  { kode: "327308", nama: "Bandung Kulon", kabupatenKode: "3273" },
  { kode: "327309", nama: "Bojongloa Kaler", kabupatenKode: "3273" },
  { kode: "327310", nama: "Bojongloa Kidul", kabupatenKode: "3273" },
  { kode: "327311", nama: "Buahbatu", kabupatenKode: "3273" },
  { kode: "327312", nama: "Cibeunying Kaler", kabupatenKode: "3273" },
  { kode: "327313", nama: "Cibeunying Kidul", kabupatenKode: "3273" },
  { kode: "327314", nama: "Cibiru", kabupatenKode: "3273" },
  { kode: "327315", nama: "Cicendo", kabupatenKode: "3273" },
  { kode: "327316", nama: "Gedebage", kabupatenKode: "3273" },
  { kode: "327317", nama: "Kiaracondong", kabupatenKode: "3273" },
  { kode: "327318", nama: "Mandalajati", kabupatenKode: "3273" },
  { kode: "327319", nama: "Panyileukan", kabupatenKode: "3273" },
  { kode: "327320", nama: "Rancasari", kabupatenKode: "3273" },
  { kode: "327321", nama: "Regol", kabupatenKode: "3273" },
  { kode: "327322", nama: "Sumur Bandung", kabupatenKode: "3273" },
  { kode: "327323", nama: "Ujungberung", kabupatenKode: "3273" },
  { kode: "327324", nama: "Arcamanik", kabupatenKode: "3273" },
  { kode: "327325", nama: "Astana Anyar", kabupatenKode: "3273" },
  { kode: "327326", nama: "Antapani", kabupatenKode: "3273" },
  { kode: "327327", nama: "Bandung Kidul", kabupatenKode: "3273" },
  { kode: "327328", nama: "Batununggal", kabupatenKode: "3273" },
  { kode: "327329", nama: "Bojongloa Kaler", kabupatenKode: "3273" },
  { kode: "327330", nama: "Lengkong", kabupatenKode: "3273" },

  // Jakarta Selatan (3174)
  { kode: "317401", nama: "Kebayoran Baru", kabupatenKode: "3174" },
  { kode: "317402", nama: "Kebayoran Lama", kabupatenKode: "3174" },
  { kode: "317403", nama: "Pesanggrahan", kabupatenKode: "3174" },
  { kode: "317404", nama: "Cilandak", kabupatenKode: "3174" },
  { kode: "317405", nama: "Pasarminggu", kabupatenKode: "3174" },
  { kode: "317406", nama: "Jagakarsa", kabupatenKode: "3174" },
  { kode: "317407", nama: "Mampang Prapatan", kabupatenKode: "3174" },
  { kode: "317408", nama: "Pancoran", kabupatenKode: "3174" },
  { kode: "317409", nama: "Tebet", kabupatenKode: "3174" },
  { kode: "317410", nama: "Setiabudi", kabupatenKode: "3174" },

  // Jakarta Pusat (3171)
  { kode: "317101", nama: "Gambir", kabupatenKode: "3171" },
  { kode: "317102", nama: "Tanah Abang", kabupatenKode: "3171" },
  { kode: "317103", nama: "Menteng", kabupatenKode: "3171" },
  { kode: "317104", nama: "Senen", kabupatenKode: "3171" },
  { kode: "317105", nama: "Johar Baru", kabupatenKode: "3171" },
  { kode: "317106", nama: "Cempaka Putih", kabupatenKode: "3171" },
  { kode: "317107", nama: "Kemayoran", kabupatenKode: "3171" },
  { kode: "317108", nama: "Sawah Besar", kabupatenKode: "3171" },

  // Bogor (3201 - Kabupaten)
  { kode: "320101", nama: "Cibinong", kabupatenKode: "3201" },
  { kode: "320102", nama: "Citeureup", kabupatenKode: "3201" },
  { kode: "320103", nama: "Cibungbulang", kabupatenKode: "3201" },
  { kode: "320104", nama: "Cigombong", kabupatenKode: "3201" },
  { kode: "320105", nama: "Cileungsi", kabupatenKode: "3201" },
  { kode: "320106", nama: "Ciawi", kabupatenKode: "3201" },
  { kode: "320107", nama: "Cisarua", kabupatenKode: "3201" },
  { kode: "320108", nama: "Jasinga", kabupatenKode: "3201" },
  { kode: "320109", nama: "Leuwiliang", kabupatenKode: "3201" },
  { kode: "320110", nama: "Parung", kabupatenKode: "3201" },

  // Surabaya (3578)
  { kode: "357801", nama: "Tegalsari", kabupatenKode: "3578" },
  { kode: "357802", nama: "Genteng", kabupatenKode: "3578" },
  { kode: "357803", nama: "Bubutan", kabupatenKode: "3578" },
  { kode: "357804", nama: "Simokerto", kabupatenKode: "3578" },
  { kode: "357805", nama: "Pabean Cantian", kabupatenKode: "3578" },
  { kode: "357806", nama: "Semampir", kabupatenKode: "3578" },
  { kode: "357807", nama: "Krembangan", kabupatenKode: "3578" },
  { kode: "357808", nama: "Kenjeran", kabupatenKode: "3578" },
  { kode: "357809", nama: "Bulak", kabupatenKode: "3578" },
  { kode: "357810", nama: "Sukolilo", kabupatenKode: "3578" },

  // Denpasar (5171)
  { kode: "517101", nama: "Denpasar Selatan", kabupatenKode: "5171" },
  { kode: "517102", nama: "Denpasar Timur", kabupatenKode: "5171" },
  { kode: "517103", nama: "Denpasar Utara", kabupatenKode: "5171" },
  { kode: "517104", nama: "Denpasar Barat", kabupatenKode: "5171" },

  // Medan (1271)
  { kode: "127101", nama: "Medan Tuntungan", kabupatenKode: "1271" },
  { kode: "127102", nama: "Medan Johor", kabupatenKode: "1271" },
  { kode: "127103", nama: "Medan Amplas", kabupatenKode: "1271" },
  { kode: "127104", nama: "Medan Denai", kabupatenKode: "1271" },
  { kode: "127105", nama: "Medan Area", kabupatenKode: "1271" },
  { kode: "127106", nama: "Medan Kota", kabupatenKode: "1271" },
  { kode: "127107", nama: "Medan Maimun", kabupatenKode: "1271" },
  { kode: "127108", nama: "Medan Polonia", kabupatenKode: "1271" },

  // Semarang (3374)
  { kode: "337401", nama: "Semarang Tengah", kabupatenKode: "3374" },
  { kode: "337402", nama: "Semarang Utara", kabupatenKode: "3374" },
  { kode: "337403", nama: "Semarang Timur", kabupatenKode: "3374" },
  { kode: "337404", nama: "Semarang Selatan", kabupatenKode: "3374" },
  { kode: "337405", nama: "Semarang Barat", kabupatenKode: "3374" },
  { kode: "337406", nama: "Gajahmungkur", kabupatenKode: "3374" },
  { kode: "337407", nama: "Candisari", kabupatenKode: "3374" },
  { kode: "337408", nama: "Genuk", kabupatenKode: "3374" },
  { kode: "337409", nama: "Gayamsari", kabupatenKode: "3374" },
  { kode: "337410", nama: "Pedurungan", kabupatenKode: "3374" },
  { kode: "337411", nama: "Banyumanik", kabupatenKode: "3374" },
  { kode: "337412", nama: "Tembalang", kabupatenKode: "3374" },
  { kode: "337413", nama: "Tugu", kabupatenKode: "3374" },
  { kode: "337414", nama: "Mijen", kabupatenKode: "3374" },
  { kode: "337415", nama: "Gunungpati", kabupatenKode: "3374" },
  { kode: "337416", nama: "Ngaliyan", kabupatenKode: "3374" },
];

// ============================================================
// HELPER FUNCTIONS
// ============================================================

export const getKabupatenByProvinsi = (provinsiKode: string): MasterKabupaten[] => {
  return MASTER_KABUPATEN.filter((k) => k.provinsiKode === provinsiKode);
};

export const getKecamatanByKabupaten = (kabupatenKode: string): MasterKecamatan[] => {
  return MASTER_KECAMATAN.filter((k) => k.kabupatenKode === kabupatenKode);
};

export const getProvinsiByKode = (kode: string): MasterProvinsi | undefined => {
  return MASTER_PROVINSI.find((p) => p.kode === kode);
};

export const getKabupatenByKode = (kode: string): MasterKabupaten | undefined => {
  return MASTER_KABUPATEN.find((k) => k.kode === kode);
};

export const getKecamatanByKode = (kode: string): MasterKecamatan | undefined => {
  return MASTER_KECAMATAN.find((k) => k.kode === kode);
};
